"""v1.1 user fields

Revision ID: 0f6167f47247
Revises: 35f30ea9a34c
Create Date: 2026-07-13 14:25:04.753909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f6167f47247'
down_revision: Union[str, None] = '35f30ea9a34c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('customer_code', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('dob', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('language', sa.String(length=5), nullable=True))
    op.create_index(op.f('ix_users_customer_code'), 'users', ['customer_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_customer_code'), table_name='users')
    op.drop_column('users', 'language')
    op.drop_column('users', 'dob')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'customer_code')
    # ### end Alembic commands ###
