"""v1.1 all changes

Revision ID: ad2b95504493
Revises: 0f6167f47247
Create Date: 2026-07-15 13:05:36.283993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad2b95504493'
down_revision: Union[str, None] = '0f6167f47247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrators', sa.Column('retailer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'administrators', 'retailers', ['retailer_id'], ['id'])
    op.add_column('orders', sa.Column('fulfillment', sa.String(length=12), nullable=False, server_default='delivery'))
    op.add_column('orders', sa.Column('tax', sa.Float(), nullable=False, server_default='0'))
    op.add_column('products', sa.Column('guide_en', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('guide_rw', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('guide_fr', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('guide_video', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'guide_video')
    op.drop_column('products', 'guide_fr')
    op.drop_column('products', 'guide_rw')
    op.drop_column('products', 'guide_en')
    op.drop_column('orders', 'tax')
    op.drop_column('orders', 'fulfillment')
    op.drop_constraint(None, 'administrators', type_='foreignkey')
    op.drop_column('administrators', 'retailer_id')
    # ### end Alembic commands ###
