"""preorder request and reservation fields

Revision ID: de0098880725
Revises: de9b29e6e0cc
Create Date: 2026-07-21 12:57:52.537616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de0098880725'
down_revision: Union[str, None] = 'de9b29e6e0cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preorders', sa.Column('needed_by', sa.String(length=20), nullable=True))
    op.add_column('preorders', sa.Column('reason', sa.Text(), nullable=True))
    op.add_column('preorders', sa.Column('accept_pay', sa.Integer(), nullable=True))
    op.add_column('preorders', sa.Column('accept_delay', sa.Integer(), nullable=True))
    op.add_column('preorders', sa.Column('req_province', sa.String(length=80), nullable=True))
    op.add_column('preorders', sa.Column('req_district', sa.String(length=80), nullable=True))
    op.add_column('preorders', sa.Column('req_sector', sa.String(length=80), nullable=True))
    op.add_column('preorders', sa.Column('available_on', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preorders', 'available_on')
    op.drop_column('preorders', 'req_sector')
    op.drop_column('preorders', 'req_district')
    op.drop_column('preorders', 'req_province')
    op.drop_column('preorders', 'accept_delay')
    op.drop_column('preorders', 'accept_pay')
    op.drop_column('preorders', 'reason')
    op.drop_column('preorders', 'needed_by')
    # ### end Alembic commands ###
