"""delivery distances cache

Revision ID: de9b29e6e0cc
Revises: a74e8bac4eab
Create Date: 2026-07-20 10:03:57.692927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9b29e6e0cc'
down_revision: Union[str, None] = 'a74e8bac4eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_distances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('retailer_id', sa.Integer(), nullable=False),
    sa.Column('village_key', sa.String(length=200), nullable=False),
    sa.Column('km', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('retailer_id', 'village_key', name='uq_delivery_distance_pair')
    )
    op.create_index(op.f('ix_delivery_distances_retailer_id'), 'delivery_distances', ['retailer_id'], unique=False)
    op.create_index(op.f('ix_delivery_distances_village_key'), 'delivery_distances', ['village_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_distances_village_key'), table_name='delivery_distances')
    op.drop_index(op.f('ix_delivery_distances_retailer_id'), table_name='delivery_distances')
    op.drop_table('delivery_distances')
    # ### end Alembic commands ###
